[package]
name = "api"
version = "0.1.0"
edition = "2018"

[dependencies]
juniper = "0.10"
juniper_hyper = "0.1.0"
hyper = "0.13"
tokio = { version = "0.2", features = ["full"] }
log = "0.4"
pretty_env_logger = "0.3"
futures = "0.1"

