name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: yarn --immutable

      - name: Run yarn build
        run: yarn build:frontend

#      - name: Run cargo build
#        uses: actions-rs/cargo@v1
#        with:
#          command: build
